import json
import re
from typing import Any


def clean_json_block(text: str) -> str:
    """
    Remove Markdown code fences and extract a JSON object/list
    from an AI response.
    """

    if not text:
        raise ValueError("Empty AI response.")

    cleaned = text.strip()

    # Remove ```json and ``` blocks.
    cleaned = re.sub(r"^```json\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^```\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)

    cleaned = cleaned.strip()

    # Try to find JSON array.
    first_array = cleaned.find("[")
    last_array = cleaned.rfind("]")

    if first_array != -1 and last_array != -1:
        return cleaned[first_array:last_array + 1]

    # Try to find JSON object.
    first_object = cleaned.find("{")
    last_object = cleaned.rfind("}")

    if first_object != -1 and last_object != -1:
        return cleaned[first_object:last_object + 1]

    return cleaned


def parse_json_response(text: str) -> Any:
    """
    Clean and parse JSON generated by the AI.
    """

    cleaned = clean_json_block(text)

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Could not parse Gemini response as JSON: {exc}"
        ) from exc